In [1]:
import pandas as pd
import numpy as np  
import tensorflow as tf

In [15]:
df = pd.read_csv(r"C:\Users\LIKHITH\OneDrive\Desktop\Data science\Data_files\Churn_Modelling.csv")  # Load data from a CSV file

In [16]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [17]:
tf.__version__

'2.20.0'

In [18]:
df.head(4)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0

In [19]:
X = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [20]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [21]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [23]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [25]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]],
      shape=(10000, 12), dtype=object)

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [27]:
X

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 12))

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.20, random_state=0)

### Building the ANN

# Initializing the ANN

In [32]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [33]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [34]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [35]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [37]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [38]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 850us/step - accuracy: 0.7768 - loss: 0.5624
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step - accuracy: 0.7959 - loss: 0.4820
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 800us/step - accuracy: 0.8016 - loss: 0.4502
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.8095 - loss: 0.4329
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.8152 - loss: 0.4220
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step - accuracy: 0.8230 - loss: 0.4122
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 742us/step - accuracy: 0.8281 - loss: 0.4017
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.8345 - loss: 0.3915
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 790us/step - accuracy: 0.8381 - loss: 0.3819
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 776us/step - accuracy: 0.8440 - loss: 0.3738
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step - accuracy: 0.8465 - loss: 0.3677
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.8490 - loss: 0.3623
Epoch 13/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - accuracy: 0.8519 - loss: 0.3586
Epoch 14/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.8518 - loss: 0.3557
Epoch 15/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step - accuracy: 0.8524 - loss: 0.3537
Epoch 16/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 747us/step - accuracy: 0.8547 - loss: 0.3517
Epoch 17/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - accuracy: 0.8558 - loss: 0.3505
Epoch 18/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.8556 - loss: 0.3495
Epoch 19/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 755us/step - accuracy: 0.8565 - loss: 0.3481
Epoch 20/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 754us/step - accuracy: 0.8591 - loss: 0.3470
Epoch 21/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step - accuracy: 0.8576 - loss: 0.3463
Epoch 22/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.8597 - loss: 0.3457
Epoch 23/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.8586 - loss: 0.3448
Epoch 24/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.8581 - loss: 0.3446
Epoch 25/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.8580 - loss: 0.3439
Epoch 26/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.8601 - loss: 0.3430
Epoch 27/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.8612 - loss: 0.3423
Epoch 28/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.8616 - loss: 0.3418
Epoch 29/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.8595 - loss: 0.3416
Epoch 30/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8614 - loss: 0.3416
Epoch 31/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.8621 - loss: 0.3410
Epoch 32/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.8599 - loss: 0.3401
Epoch 33/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.8612 - loss: 0.3401
Epoch 34/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.8616 - loss: 0.3395
Epoch 35/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8626 - loss: 0.3393
Epoch 36/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.8602 - loss: 0.3394
Epoch 37/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.8610 - loss: 0.3394
Epoch 38/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.8614 - loss: 0.3392
Epoch 39/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.8611 - loss: 0.3383
Epoch 40/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.8593 - loss: 0.3384
Epoch 41/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.8616 - loss: 0.3383
Epoch 42/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.8602 - loss: 0.3388
Epoch 43/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.8627 - loss: 0.3382
Epoch 44/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.8616 - loss: 0.3373
Epoch 45/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.8589 - loss: 0.3373
Epoch 46/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.8590 - loss: 0.3368
Epoch 47/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.8608 - loss: 0.3371
Epoch 48/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.8629 - loss: 0.3371
Epoch 49/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.8612 - loss: 0.3369
Epoch 50/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.8619 - loss: 0.3366

# Making the predictions and evaluating the model

### Predicting the Test set results

In [39]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]

### Making the Confusion Matrix

In [40]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1510   85]
 [ 192  213]]