In [3]:
!pip install langchain
!pip install watermark
!pip install openai
!pip install langchain-experimental
!pip install tabulate

Requirement already satisfied: langchain in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.2.8)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.8 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain) (1.2.17)
Requirement already satisfied: langgraph<1.1.0,>=1.0.7 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain) (1.0.7)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain) (2.12.5)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain) (0.6.8)
Requirement already satisfied: packaging>=23.2.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain) (26.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.8->langchain) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langgraph<1.1.0,>=1.0.7->langchain) (4.0.0)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.7 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langgraph<1.1.0,>=1.0.7->langchain) (1.0.7)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langgraph<1.1.0,>=1.0.7->langchain) (0.3.3)
Requirement already satisfied: xxhash>=3.5.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langgraph<1.1.0,>=1.0.7->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.7->langchain) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.7->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.7->langchain) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain) (0.25.0)
Requirement already satisfied: anyio in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.7->langchain) (4.12.1)
Requirement already satisfied: certifi in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.7->langchain) (2026.1.4)
Requirement already satisfied: httpcore==1.* in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.7->langchain) (1.0.9)
Requirement already satisfied: idna in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.7->langchain) (2.10)
Requirement already satisfied: h11>=0.16 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.7->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain) (2.6.3)
Collecting watermark
  Downloading watermark-2.6.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: ipython>=6.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from watermark) (9.10.0)
Requirement already satisfied: importlib-metadata>=1.4 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from watermark) (8.7.1)
Requirement already satisfied: setuptools in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from watermark) (65.5.0)
Requirement already satisfied: zipp>=3.20 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from importlib-metadata>=1.4->watermark) (3.23.0)
Requirement already satisfied: colorama>=0.4.4 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from ipython>=6.0->watermark) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from ipython>=6.0->watermark) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from ipython>=6.0->watermark) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from ipython>=6.0->watermark) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from ipython>=6.0->watermark) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from ipython>=6.0->watermark) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from ipython>=6.0->watermark) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from ipython>=6.0->watermark) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from ipython>=6.0->watermark) (5.14.3)
Requirement already satisfied: typing_extensions>=4.6 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from ipython>=6.0->watermark) (4.15.0)
Requirement already satisfied: wcwidth in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.0->watermark) (0.5.3)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from jedi>=0.18.1->ipython>=6.0->watermark) (0.8.5)
Requirement already satisfied: executing>=1.2.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.0->watermark) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.0->watermark) (3.0.1)
Requirement already satisfied: pure-eval in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.0->watermark) (0.2.3)
Downloading watermark-2.6.0-py3-none-any.whl (13 kB)
Installing collected packages: watermark
Successfully installed watermark-2.6.0
Requirement already satisfied: openai in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.26.0)
Requirement already satisfied: anyio<5,>=3.5.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from openai) (2.12.5)
Requirement already satisfied: sniffio in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from anyio<5,>=3.5.0->openai) (2.10)
Requirement already satisfied: certifi in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: colorama in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tqdm>4->openai) (0.4.6)
Collecting langchain-experimental
  Downloading langchain_experimental-0.4.1-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-experimental) (1.2.17)
Collecting langchain-community<1.0.0,>=0.4.0 (from langchain-experimental)
  Using cached langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading langchain_classic-1.0.3-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.0.48)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (6.0.3)
Collecting aiohttp<4.0.0,>=3.8.3 (from langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Downloading aiohttp-3.13.4-cp311-cp311-win_amd64.whl.metadata (8.4 kB)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (9.1.2)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Using cached dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Using cached pydantic_settings-2.13.1-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.6.8)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Using cached httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: numpy>=1.26.2 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.4.2)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Using cached frozenlist-1.8.0-cp311-cp311-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Using cached multidict-6.7.1-cp311-cp311-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Using cached propcache-0.4.1-cp311-cp311-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Using cached yarl-1.23.0-cp311-cp311-win_amd64.whl.metadata (82 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Using cached marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Using cached typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting langchain-core<2.0.0,>=1.0.0 (from langchain-experimental)
  Downloading langchain_core-1.2.23-py3-none-any.whl.metadata (4.4 kB)
Collecting langchain-text-splitters<2.0.0,>=1.1.1 (from langchain-classic<2.0.0,>=1.0.0->langchain-community<1.0.0,>=0.4.0->langchain-experimental)
  Using cached langchain_text_splitters-1.1.1-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.12.5)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-experimental) (1.33)
Requirement already satisfied: packaging>=23.2.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-experimental) (26.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-experimental) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-experimental) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.0->langchain-experimental) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.25.0)
Requirement already satisfied: anyio in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (4.12.1)
Requirement already satisfied: certifi in C:\Users\LIKHITH\AppData\Local\Programs\Python\Python311\Lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2026.1.4)

In [6]:
import os
import warnings
import pandas as pd
warnings.filterwarnings("ignore")

In [7]:
from langchain_experimental.agents import create_pandas_dataframe_agent
from langchain_openai import ChatOpenAI

In [8]:
from langchain_openai import OpenAI

In [9]:
os.environ["OPENAI_API_KEY"] = "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"

In [10]:
df = pd.read_csv(r"C:\Users\LIKHITH\OneDrive\Desktop\Data science\Data_files\titanic dataset.csv")

In [11]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [13]:
df1=df.copy()

In [14]:
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S